### ISSUE TITLE
'undefined symbol: __intel_sse2_strcpy'

### ISSUE THREAD

**Issue by YuuuuXie** [abelcarreras/phonolammps#1]
Hi I get an error when I try to run python as the `examples/Si` shows:

```
Traceback (most recent call last):
  File "phonolammps", line 8, in <module>
    from phonolammps import Phonolammps
  File "/n/home08/xiey/.conda/envs/venv/lib/python3.6/site-packages/phonolammps/__init__.py", line 6, in <module>
    from phonopy.file_IO import write_FORCE_CONSTANTS, write_force_constants_to_hdf5
  File "/n/home08/xiey/.conda/envs/venv/lib/python3.6/site-packages/phonopy/__init__.py", line 36, in <module>
    from phonopy.api_phonopy import Phonopy
  File "/n/home08/xiey/.conda/envs/venv/lib/python3.6/site-packages/phonopy/api_phonopy.py", line 42, in <module>
    from phonopy.structure.symmetry import Symmetry, symmetrize_borns_and_epsilon
  File "/n/home08/xiey/.conda/envs/venv/lib/python3.6/site-packages/phonopy/structure/symmetry.py", line 36, in <module>
    import phonopy.structure.spglib as spg
  File "/n/home08/xiey/.conda/envs/venv/lib/python3.6/site-packages/phonopy/structure/spglib.py", line 35, in <module>
    from phonopy import _spglib as spg
ImportError: /n/home08/xiey/.conda/envs/venv/lib/python3.6/site-packages/phonopy/_spglib.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __intel_sse2_strcpy
```

I tried both icc and gcc to install, but neither worked. Do you have any idea what's wrong with it?

**Comment by YuuuuXie** [comment]
I solved it by re-install `phonopy` with `conda` instead of `pip`. Though I still don't know why....
